/// Flutter icons DarwinFont
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DarwinFont
///      fonts:
///       - asset: fonts/DarwinFont.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DarwinFont {
  DarwinFont._();

  static const _kFontFam = 'DarwinFont';

  static const IconData bell = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData cancel = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData check = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData chevron_down = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData chevron_left = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData chevron_right = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData clock = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData emoji_happy = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData emoji_ok = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData emoji_sad = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData emoji_too_happy = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData emoji_too_sad = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData files = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData gps = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData layers = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData check_round = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData mail = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData map = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData mic = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData more_horizontal = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData play = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData record = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData refresh = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData signature = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData sort = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData star_outline = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData star_solid = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData stop = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData undo = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData users = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData video = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData logo_animatable = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData logo = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData star_solid_half = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData round_ring = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData cancel_round = const IconData(0xe82a, fontFamily: _kFontFam);
}
